<a href="https://colab.research.google.com/github/25061116/data_science_w1/blob/main/Tutorial_Week_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
#1
array_2x2 = np.array([[1,2], [3,4]])
print(array_2x2)
print(f"shape: {array_2x2.shape}\n")

[[1 2]
 [3 4]]
shape: (2, 2)



In [12]:
#2
array_3x4 = np.random.rand(3, 4)
print(array_3x4)
print(f"shape: {array_3x4.shape}\n")

[[0.40333421 0.01950389 0.28263018 0.52042462]
 [0.33979284 0.04808742 0.68630357 0.67036818]
 [0.98343122 0.16296049 0.71502071 0.07786925]]
shape: (3, 4)



In [29]:
#3
ones_array = np.ones((3,3))
zeros_array = np.zeros((2,4))


print("zeroes array (2x4):")
print(zeros_array)
print("ones array (2x4):")
print(ones_array)
print(f"ones shape: {ones_array.shape}, zeroes shape: {zeros_array.shape}\n")



zeroes array (2x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array (2x4):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
ones shape: (3, 3), zeroes shape: (2, 4)



In [36]:
#4
random_3x6 = np.random.rand(3, 6)
transposed = random_3x6.T
print("original (3x6)")
print(random_3x6)
print("transported (6x3)")
print(transposed)
print(f"shape: {random_3x6.shape}, {transposed.shape}\n")



original (3x6)
[[0.54700274 0.35272721 0.15647504 0.70964516 0.55546505 0.26260105]
 [0.64731906 0.18291968 0.78368073 0.03840317 0.56151972 0.2939914 ]
 [0.07580814 0.19811607 0.40125807 0.03109839 0.35306057 0.14920081]]
transported (6x3)
[[0.54700274 0.64731906 0.07580814]
 [0.35272721 0.18291968 0.19811607]
 [0.15647504 0.78368073 0.40125807]
 [0.70964516 0.03840317 0.03109839]
 [0.55546505 0.56151972 0.35306057]
 [0.26260105 0.2939914  0.14920081]]
shape: (3, 6), (6, 3)



In [45]:
#5
n, p, m, = 4, 3, 5,
array1 = np.random.rand(n , p)
array2 =  np.random.rand(p , m)
dot_product = np.dot(array1,array2)

print(f"Array 1 ({n}x{p}):")
print(array1)
print(f"array 2 ({p}x{m})")
print(array2)
print(f"Dot product result ({n}x{m})")
print(dot_product)
print(f"Dot product shape: {dot_product.shape}")


Array 1 (4x3):
[[0.09593356 0.31464536 0.58844214]
 [0.15162482 0.0513999  0.14876465]
 [0.69668721 0.84693293 0.93070883]
 [0.06787463 0.64136102 0.21571545]]
array 2 (3x5)
[[0.9320704  0.10642964 0.59451253 0.9122546  0.2456151 ]
 [0.638241   0.50728745 0.7640028  0.32126833 0.17744951]
 [0.7921341  0.80971366 0.69481878 0.64208468 0.35202295]]
Dot product result (4x5)
[[0.75636148 0.64629545 0.70628428 0.5664311  0.28654153]
 [0.29197208 0.16266867 0.23277699 0.2503531  0.0987308 ]
 [1.92715505 1.25739426 1.70792238 1.50524272 0.6490356 ]
 [0.64348239 0.50724602 0.68023708 0.40647551 0.20641702]]
Dot product shape: (4, 5)
